version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  cpihole:
    build:
       context: ./cpihole
    container_name: cpihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8081:80/tcp"
      - "4431:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    # Volumes store your data between container upgrades
    volumes:
       - etcpihole:/etc/pihole/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  sniproxyvpn:
    build:
      context: ./sniproxyvpn
    container_name: sniproxyvpn
    privileged: true
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      VPN_USERNAME: ${VPN_USERNAME}
      VPN_PASSWORD: ${VPN_PASSWORD}
      VPN_OPTIONS: ${VPN_OPTIONS}
      CIDR_NETWORK: ${CIDR_NETWORK}
      VPN_DNS1: ${VPN_DNS1}
      VPN_DNS2: ${VPN_DNS2}
    restart: unless-stopped
volumes:
  etcpihole:
    driver: local
